from pathlib import Path
import importlib.util
import inspect
import json

import numpy as np
import pytest

import master_equation_initial_correlations as meic
from master_equation_initial_correlations import (
    BathParams,
    NumericsConfig,
    SystemParams,
    doctor,
)
from master_equation_initial_correlations._types import SimulationParams
from master_equation_initial_correlations.blackbox import BosonicBathSolverWC
from master_equation_initial_correlations.simulation import run_simulation


FAST_NUMERICS = NumericsConfig(
    omega_nodes=24,
    omega_max=60.0,
    lambda_nodes=8,
    initial_state_omega_nodes=12,
    initial_state_lambda_nodes=6,
    initial_state_zeta_nodes=6,
    coefficient_time_step=0.00125,
    correlation_tau_step=0.00125,
    coefficient_t_max=0.05,
    correlation_tau_max=0.05,
    fortran_t_final=0.05,
)


def _compiler_ready() -> bool:
    return bool(doctor()["compiler_found"])


def test_run_pure_dephasing_free_form_n1(tmp_path: Path) -> None:
    result = run_simulation(
        SimulationParams(
            bath="bosonic",
            model="pure-dephasing",
            spectral="ohmic",
            N=1,
            epsilon0=4.0,
            epsilon=4.0,
            delta0=0.0,
            delta=0.0,
        ),
        tmp_path / "pure-n1",
    )
    assert result.exact_correlated_error is not None
    assert result.exact_correlated_error <= 1.0e-12


def test_run_pure_dephasing_free_form_n4(tmp_path: Path) -> None:
    result = run_simulation(
        SimulationParams(
            bath="bosonic",
            model="pure-dephasing",
            spectral="ohmic",
            N=4,
            epsilon0=4.0,
            epsilon=4.0,
            delta0=0.0,
            delta=0.0,
        ),
        tmp_path / "pure-n4",
    )
    assert result.exact_correlated_error is not None
    assert result.exact_correlated_error <= 1.0e-12


def test_run_pure_dephasing_second_moment(tmp_path: Path) -> None:
    result = run_simulation(
        SimulationParams(
            bath="bosonic",
            model="pure-dephasing",
            spectral="ohmic",
            observable="jx^2",
            N=2,
            epsilon0=4.0,
            epsilon=4.0,
            delta0=0.0,
            delta=0.0,
        ),
        tmp_path / "pure-jx2",
        verify=False,
    )
    assert result.verification_performed is False
    assert (result.output_dir / "exact-correlated.dat").exists()


def test_pure_dephasing_rejects_transverse_terms(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="delta0=0 and delta=0"):
        run_simulation(
            SimulationParams(
                bath="bosonic",
                model="pure-dephasing",
                spectral="ohmic",
                N=1,
                epsilon=4.0,
                delta0=0.5,
                delta=0.0,
            ),
            tmp_path / "bad-pure",
        )


def test_subohmic_requires_explicit_s(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="sub-Ohmic spectra require s"):
        run_simulation(
            SimulationParams(bath="bosonic", model="spin-boson", spectral="subohmic", observable="jx", N=4),
            tmp_path / "bad-subohmic",
        )


def test_superohmic_requires_s_greater_than_one(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="super-Ohmic spectra require s > 1"):
        run_simulation(
            SimulationParams(bath="spin", model="spin-environment", spectral="superohmic", observable="jx", N=4, s=0.5),
            tmp_path / "bad-superohmic",
        )


def test_rejects_fractional_N(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="N must be a positive integer"):
        run_simulation(
            SimulationParams(
                bath="bosonic",
                model="pure-dephasing",
                spectral="ohmic",
                N=1.5,  # type: ignore[arg-type]
                epsilon=4.0,
                delta0=0.0,
                delta=0.0,
            ),
            tmp_path / "bad-N",
        )


def test_exact_output_has_headers_and_overwrite_protection(tmp_path: Path) -> None:
    out = tmp_path / "pure"
    run_simulation(
        SimulationParams(
            bath="bosonic",
            model="pure-dephasing",
            spectral="ohmic",
            N=1,
            epsilon=4.0,
            delta0=0.0,
            delta=0.0,
        ),
        out,
        verbose=False,
    )
    assert (out / "exact-correlated.dat").read_text().startswith("# Generated by")
    with pytest.raises(FileExistsError):
        run_simulation(
            SimulationParams(
                bath="bosonic",
                model="pure-dephasing",
                spectral="ohmic",
                N=1,
                epsilon=4.0,
                delta0=0.0,
                delta=0.0,
            ),
            out,
            verbose=False,
        )


def test_blackbox_pure_dephasing_is_ram_only_by_default(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.chdir(tmp_path)
    system = SystemParams(N=1, epsilon0=4.0, epsilon=4.0, delta0=0.0, delta=0.0)
    bath = BathParams(bath_type="bosonic", kind="ohmic", s=1.0, beta=1.0, coupling=0.05, omega_c=5.0)
    tlist = np.linspace(0.0, 1.0, 6)

    wc = meic.exact.solve(system, bath, tlist=tlist, e_ops=["jx", "jz"], correlations="with")
    woc = meic.exact.solve(system, bath, tlist=tlist, e_ops=["jx"], correlations="without")

    assert wc.times.tolist() == pytest.approx(tlist.tolist())
    assert len(wc.expect) == 2
    assert set(wc.e_data) == {"jx", "jz"}
    assert wc.metadata["initial_state"]["source"] == "analytical_correlated_or_uncorrelated_pure_dephasing_construction"
    assert wc.metadata["initial_state"]["custom_initial_state_supported"] is False
    assert woc.branch == "without_correlations"
    assert not any(tmp_path.iterdir())


def test_result_save_is_explicit_and_headered(tmp_path: Path) -> None:
    system = SystemParams(N=1, epsilon0=4.0, epsilon=4.0, delta0=0.0, delta=0.0)
    bath = BathParams(bath_type="bosonic", kind="ohmic", s=1.0, beta=1.0, coupling=0.05, omega_c=5.0)
    result = meic.exact.solve(system, bath, tlist=np.linspace(0.0, 0.5, 6), e_ops=["jx", "jz"])

    destination = result.save(tmp_path / "saved-result")

    saved_jx = (destination / "expect-jx.dat").read_text()
    assert saved_jx.startswith("# Generated by")
    assert "initial_state_source: analytical_correlated_or_uncorrelated_pure_dephasing_construction" in saved_jx
    metadata = json.loads((destination / "result_metadata.json").read_text())
    assert metadata["observables"] == ["jx", "jz"]
    assert set(metadata["parameters_by_observable"]) == {"jx", "jz"}
    assert "multiple observables" in metadata["parameters"]["note"]
    assert metadata["metadata"]["initial_state"]["custom_initial_state_supported"] is False
    assert result.as_dict()["expect"]["jx"].shape == result.times.shape
    if importlib.util.find_spec("pandas") is None:
        with pytest.raises(ImportError, match="requires pandas"):
            result.to_dataframe()
    else:
        assert result.to_dataframe().columns.tolist() == ["t", "jx", "jz"]
    with pytest.raises(FileExistsError):
        result.save(destination)
    with pytest.raises(FileNotFoundError, match="no retained artifacts"):
        result.save(tmp_path / "no-artifacts", include_artifacts=True)


def test_blackbox_tlist_validation() -> None:
    system = SystemParams(N=1, epsilon=4.0)
    bath = BathParams(bath_type="bosonic", kind="ohmic", s=1.0)
    with pytest.raises(ValueError, match="start at 0.0") as start_error:
        meic.exact.solve(system, bath, tlist=np.linspace(0.1, 1.0, 5))
    assert "exact analytical pure-dephasing solver" in str(start_error.value)
    assert "Fortran-backed" not in str(start_error.value)
    with pytest.raises(ValueError, match="uniformly spaced") as spacing_error:
        meic.exact.solve(system, bath, tlist=np.array([0.0, 0.1, 0.3]))
    assert "exact analytical pure-dephasing solver" in str(spacing_error.value)
    assert "Fortran-backed" not in str(spacing_error.value)


def test_public_master_equation_rejects_custom_initial_state() -> None:
    system = SystemParams(N=2, epsilon0=4.0, epsilon=2.5, delta0=0.5, delta=0.5)
    bath = BathParams(bath_type="bosonic", kind="ohmic", s=1.0)
    rho0 = np.eye(3, dtype=complex) / 3.0
    with pytest.raises(ValueError, match="custom initial_state is not supported"):
        meic.solve(system, bath, tlist=np.linspace(0.0, 0.1, 2), e_ops=["jx"], initial_state=rho0)


def test_bath_params_are_keyword_only() -> None:
    with pytest.raises(TypeError):
        BathParams("ohmic")


def test_public_api_does_not_export_internal_solver_classes() -> None:
    assert not hasattr(meic, "BosonicBathSolverWC")
    signature = inspect.signature(BosonicBathSolverWC)
    assert "branch" not in signature.parameters
    assert "bath_type" not in signature.parameters
    assert "model" not in signature.parameters


def test_blackbox_validation_rejects_bad_spectrum_before_fortran() -> None:
    system = SystemParams(N=2, epsilon0=4.0, epsilon=2.5, delta0=0.5, delta=0.5)
    tlist = np.linspace(0.0, 0.05, 6)
    with pytest.raises(ValueError, match="Ohmic spectra use s=1"):
        meic.solve(system, BathParams(kind="ohmic", s=0.5), tlist=tlist, e_ops=["jx"])
    with pytest.raises(ValueError, match="sub-Ohmic spectra require 0 < s < 1"):
        meic.solve(system, BathParams(kind="subohmic", s=2.0), tlist=tlist, e_ops=["jx"])
    with pytest.raises(ValueError, match="spin-environment"):
        meic.solve(system, BathParams(bath_type="spin", kind="ohmic", s=1.0), tlist=tlist, e_ops=["jx"], model="spin-boson")


def test_exact_namespace_rejects_non_pure_dephasing() -> None:
    system = SystemParams(N=1, epsilon0=4.0, epsilon=4.0, delta0=0.5, delta=0.0)
    bath = BathParams(bath_type="bosonic", kind="ohmic", s=1.0)
    with pytest.raises(ValueError, match="delta0=0 and delta=0"):
        meic.exact.solve(system, bath, tlist=np.linspace(0.0, 0.1, 2), e_ops=["jx"])


def test_blackbox_nonhermitian_observable_warns() -> None:
    system = SystemParams(N=1, epsilon0=4.0, epsilon=4.0, delta0=0.0, delta=0.0)
    bath = BathParams(bath_type="bosonic", kind="ohmic", s=1.0)
    with pytest.warns(RuntimeWarning, match="not Hermitian"):
        meic.exact.solve(system, bath, tlist=np.linspace(0.0, 0.1, 2), e_ops=["jx*jy"])


def test_package_assets_do_not_ship_rendered_images() -> None:
    asset_root = Path(__file__).resolve().parents[1] / "src" / "master_equation_initial_correlations" / "_assets"
    images = [path for path in asset_root.rglob("*") if path.suffix.lower() in {".eps", ".png"}]
    assert images == []


def test_no_verify_reports_unchecked_exact_run(tmp_path: Path) -> None:
    result = run_simulation(
        SimulationParams(
            bath="bosonic",
            model="pure-dephasing",
            spectral="ohmic",
            N=1,
            epsilon=4.0,
            delta0=0.0,
            delta=0.0,
        ),
        tmp_path / "pure-no-verify",
        verify=False,
        verbose=False,
    )
    assert result.verification_performed is False
    assert result.exact_correlated_error is None


@pytest.mark.solver_rerun
def test_blackbox_fortran_solver_returns_arrays_and_saves_artifacts(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    monkeypatch.chdir(tmp_path)
    system = SystemParams(N=2, epsilon0=4.0, epsilon=2.5, delta0=0.5, delta=0.5)
    bath = BathParams(bath_type="bosonic", kind="ohmic", s=1.0, beta=1.0, coupling=0.05, omega_c=5.0)
    tlist = np.linspace(0.0, 0.05, 6)

    wc = meic.solve(system, bath, tlist=tlist, e_ops=["jx"], correlations="with", numerics=FAST_NUMERICS, save_density=True, verbose=False)
    woc = meic.solve(system, bath, tlist=tlist, e_ops=["jx"], correlations="without", numerics=FAST_NUMERICS, verbose=False)

    assert wc.times[0] == pytest.approx(1.0e-11)
    assert wc.times[1:].tolist() == pytest.approx(tlist[1:].tolist())
    assert wc.expect[0].shape == tlist.shape
    assert wc.states is not None
    assert wc.states.shape == (tlist.size, system.N + 1, system.N + 1)
    np.testing.assert_allclose(np.trace(wc.states, axis1=1, axis2=2), 1.0, atol=1.0e-8)
    np.testing.assert_allclose(wc.states, wc.states.conj().transpose(0, 2, 1), atol=1.0e-8)
    jx_from_states = np.asarray([np.trace(meic.jx(system) @ rho) for rho in wc.states])
    np.testing.assert_allclose(jx_from_states.real, wc.e_data["jx"], atol=1.0e-8)
    assert wc.metadata["initial_state"]["source"] == "generated_from_correlated_joint_system_bath_equilibrium"
    assert wc.metadata["initial_state"]["shape"] == [3, 3]
    assert woc.branch == "without_correlations"
    assert wc.artifact_dirs == {}
    with pytest.raises(FileNotFoundError, match="keep_artifacts=True"):
        wc.save(tmp_path / "no-default-artifacts", include_artifacts=True)
    assert not any(tmp_path.iterdir())

    wc_with_artifacts = meic.solve(
        system,
        bath,
        tlist=tlist,
        e_ops=["jx"],
        correlations="with",
        numerics=FAST_NUMERICS,
        keep_artifacts=True,
        verbose=False,
    )
    saved = wc_with_artifacts.save(tmp_path / "saved-fortran", include_artifacts=True)
    assert (saved / "expect-jx.dat").exists()
    assert (saved / "artifacts" / "jx" / "A.dat").exists()
    wc_with_artifacts.close()
    with pytest.raises(FileNotFoundError, match="keep_artifacts=True"):
        wc_with_artifacts.save(tmp_path / "after-close", include_artifacts=True)


def test_paper_plot_scripts_are_notebook_style_and_syntax_valid() -> None:
    root = Path(__file__).resolve().parents[1] / "paper-plots"
    for script in sorted(root.glob("figure_*.py")):
        source = script.read_text()
        compile(source, str(script), "exec")
        assert "def main" not in source
        assert ".close()" not in source


@pytest.mark.solver_rerun
def test_run_bosonic_spin_boson_n2(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(bath="bosonic", model="spin-boson", spectral="ohmic", observable="jx", N=2),
        tmp_path / "spin-boson-n2",
        verify=True,
    )
    assert result.correlated_error is not None
    assert result.correlated_error <= 1.0e-6
    assert result.uncorrelated_error is not None
    assert result.uncorrelated_error <= 1.0e-6
    assert (result.output_dir / "observable-correlated.dat").read_text().startswith("# Generated by")
    assert "input_mode: generated" in (result.output_dir / "observable-correlated.dat").read_text()
    assert (result.output_dir / "EXPX-C.DAT").exists()
    assert (result.output_dir / "sources" / "correlated_solver.f").exists()
    assert (result.output_dir / "sources" / "dimensions.inc").exists()
    assert (result.output_dir / "INSTATE.dat").exists()
    assert result.log_files is not None
    assert "correlated_compile_stderr" in result.log_files
    with pytest.raises(FileExistsError):
        run_simulation(
            SimulationParams(bath="bosonic", model="spin-boson", spectral="ohmic", observable="jx", N=2),
            result.output_dir,
            verify=False,
            verbose=False,
        )


@pytest.mark.solver_rerun
def test_run_bosonic_spin_boson_n4(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(bath="bosonic", model="spin-boson", spectral="ohmic", observable="jx", N=4),
        tmp_path / "spin-boson-n4",
        verify=True,
    )
    assert result.correlated_error is not None
    assert result.correlated_error <= 2.0e-6


@pytest.mark.solver_rerun
def test_fortran_runner_accepts_relative_output_dir(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    monkeypatch.chdir(tmp_path)
    result = run_simulation(
        SimulationParams(bath="bosonic", model="spin-boson", spectral="ohmic", observable="jx", N=2),
        Path("relative-output"),
        verify=False,
        verbose=False,
        numerics=FAST_NUMERICS,
    )
    assert result.correlated_path is not None
    assert result.correlated_path.exists()


@pytest.mark.solver_rerun
def test_run_bosonic_jx2_n4(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(
            bath="bosonic",
            model="spin-boson",
            spectral="ohmic",
            observable="jx^2",
            N=4,
            epsilon=3.5,
        ),
        tmp_path / "jx2-n4",
        verify=True,
    )
    assert result.correlated_error is not None
    assert result.correlated_error <= 2.5e-6
    assert (result.output_dir / "observable-correlated.dat").exists()
    assert not (result.output_dir / "EXPX-C.DAT").exists()


@pytest.mark.solver_rerun
def test_run_bosonic_subohmic_n4(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(bath="bosonic", model="spin-boson", spectral="subohmic", observable="jx", N=4, s=0.5),
        tmp_path / "subohmic-n4",
        verify=True,
    )
    assert result.correlated_error is not None
    assert result.correlated_error <= 2.0e-3


@pytest.mark.solver_rerun
def test_run_spin_bath_n4(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(bath="spin", model="spin-environment", spectral="ohmic", observable="jx", N=4),
        tmp_path / "spin-bath-n4",
        verify=True,
    )
    assert result.correlated_error is not None
    assert result.correlated_error <= 5.0e-7


@pytest.mark.solver_rerun
def test_run_spin_bath_jx2_without_reference(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(bath="spin", model="spin-environment", spectral="ohmic", observable="jx^2", N=4),
        tmp_path / "spin-bath-jx2-n4",
        verify=True,
        verbose=False,
    )
    assert result.example is None
    assert result.verification_performed is False
    assert (result.output_dir / "observable-correlated.dat").exists()


@pytest.mark.solver_rerun
def test_run_superohmic_bosonic_observable_sum(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(
            bath="bosonic",
            model="spin-boson",
            spectral="superohmic",
            observable="jx+jy",
            N=2,
            s=3.0,
        ),
        tmp_path / "superohmic-sum",
        verify=True,
        verbose=False,
    )
    assert result.example is None
    assert result.verification_performed is False
    assert (result.output_dir / "bathcorrelation.dat").exists()


@pytest.mark.solver_rerun
def test_run_arbitrary_bosonic_spin_boson_parameters_without_reference(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(
            bath="bosonic",
            model="spin-boson",
            spectral="ohmic",
            observable="jx",
            N=2,
            epsilon0=3.75,
            epsilon=2.25,
            delta0=0.4,
            delta=0.35,
            beta=0.8,
            coupling=0.03,
            omega_c=4.0,
        ),
        tmp_path / "arbitrary-spin-boson",
        verify=True,
        verbose=False,
    )
    assert result.example is None
    assert result.verification_performed is False
    assert result.correlated_error is None
    assert (result.output_dir / "observable-correlated.dat").exists()
    assert (result.output_dir / "params.in").exists()


@pytest.mark.solver_rerun
def test_spin_bath_subohmic_jy_with_user_numerics(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(bath="spin", model="spin-environment", spectral="subohmic", observable="jy", N=2, s=0.5),
        tmp_path / "spin-subohmic-jy",
        verify=False,
        verbose=False,
        numerics=FAST_NUMERICS,
    )
    assert result.verification_performed is False
    assert "correlation_tau_points: 41" in (result.output_dir / "bathcorrelation.dat").read_text()


@pytest.mark.solver_rerun
def test_spin_bath_superohmic_jz_saves_density(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(bath="spin", model="spin-environment", spectral="superohmic", observable="jz", N=2, s=3.0),
        tmp_path / "spin-superohmic-jz-density",
        verify=False,
        verbose=False,
        save_density=True,
        numerics=FAST_NUMERICS,
    )
    assert (result.output_dir / "density-correlated.dat").exists()
    assert (result.output_dir / "EXPZ-C.DAT").exists()


@pytest.mark.solver_rerun
def test_bosonic_custom_matrix_observable_and_initial_state(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    custom_observable = np.eye(3, dtype=complex) / 2.0
    custom_initial = np.eye(3, dtype=complex) / 3.0
    result = run_simulation(
        SimulationParams(
            bath="bosonic",
            model="spin-boson",
            spectral="superohmic",
            observable=custom_observable,
            N=2,
            s=2.0,
            initial_state=custom_initial,
        ),
        tmp_path / "bosonic-custom-matrix-state",
        verify=False,
        verbose=False,
        numerics=FAST_NUMERICS,
    )
    assert result.example is None
    assert "observable: custom_matrix" in (result.output_dir / "observable-correlated.dat").read_text()
    assert "initial_state_source: user_supplied" in (result.output_dir / "INSTATE.dat").read_text()
