from pathlib import Path

import numpy as np
import pytest

from master_equation_initial_correlations import (
    BathParams,
    BosonicBathSolver,
    NumericsConfig,
    PureDephasingSolver,
    RunConfig,
    SimulationParams,
    SystemParams,
    doctor,
    run_simulation,
)


FAST_NUMERICS = NumericsConfig(
    omega_nodes=24,
    lambda_nodes=8,
    instate_omega_nodes=12,
    instate_lambda_nodes=6,
    instate_zeta_nodes=6,
    omega_max_coefficients=60.0,
    omega_max_tau=60.0,
    omega_max_instate=60.0,
    coefficient_points=41,
    tau_points=41,
    fortran_t_final=0.05,
)


def _compiler_ready() -> bool:
    return bool(doctor()["compiler_found"])


def test_run_pure_dephasing_free_form_n1(tmp_path: Path) -> None:
    result = run_simulation(
        SimulationParams(
            bath="bosonic",
            model="pure-dephasing",
            spectral="ohmic",
            N=1,
            epsilon0=4.0,
            epsilon=4.0,
            delta0=0.0,
            delta=0.0,
        ),
        tmp_path / "pure-n1",
    )
    assert result.exact_correlated_error is not None
    assert result.exact_correlated_error <= 1.0e-12


def test_run_pure_dephasing_free_form_n4(tmp_path: Path) -> None:
    result = run_simulation(
        SimulationParams(
            bath="bosonic",
            model="pure-dephasing",
            spectral="ohmic",
            N=4,
            epsilon0=4.0,
            epsilon=4.0,
            delta0=0.0,
            delta=0.0,
        ),
        tmp_path / "pure-n4",
    )
    assert result.exact_correlated_error is not None
    assert result.exact_correlated_error <= 1.0e-12


def test_run_pure_dephasing_second_moment(tmp_path: Path) -> None:
    result = run_simulation(
        SimulationParams(
            bath="bosonic",
            model="pure-dephasing",
            spectral="ohmic",
            observable="jx^2",
            N=2,
            epsilon0=4.0,
            epsilon=4.0,
            delta0=0.0,
            delta=0.0,
        ),
        tmp_path / "pure-jx2",
        verify=False,
    )
    assert result.verification_performed is False
    assert (result.output_dir / "exact-correlated.dat").exists()


def test_pure_dephasing_rejects_transverse_terms(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="delta0=0 and delta=0"):
        run_simulation(
            SimulationParams(
                bath="bosonic",
                model="pure-dephasing",
                spectral="ohmic",
                N=1,
                epsilon=4.0,
                delta0=0.5,
                delta=0.0,
            ),
            tmp_path / "bad-pure",
        )


def test_subohmic_requires_explicit_s(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="sub-Ohmic spectra require s"):
        run_simulation(
            SimulationParams(bath="bosonic", model="spin-boson", spectral="subohmic", observable="jx", N=4),
            tmp_path / "bad-subohmic",
        )


def test_superohmic_requires_s_greater_than_one(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="super-Ohmic spectra require s > 1"):
        run_simulation(
            SimulationParams(bath="spin", model="spin-environment", spectral="superohmic", observable="jx", N=4, s=0.5),
            tmp_path / "bad-superohmic",
        )


def test_rejects_fractional_N(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="N must be a positive integer"):
        run_simulation(
            SimulationParams(
                bath="bosonic",
                model="pure-dephasing",
                spectral="ohmic",
                N=1.5,  # type: ignore[arg-type]
                epsilon=4.0,
                delta0=0.0,
                delta=0.0,
            ),
            tmp_path / "bad-N",
        )


def test_exact_output_has_headers_and_overwrite_protection(tmp_path: Path) -> None:
    out = tmp_path / "pure"
    run_simulation(
        SimulationParams(
            bath="bosonic",
            model="pure-dephasing",
            spectral="ohmic",
            N=1,
            epsilon=4.0,
            delta0=0.0,
            delta=0.0,
        ),
        out,
        verbose=False,
    )
    assert (out / "exact-correlated.dat").read_text().startswith("# Generated by")
    with pytest.raises(FileExistsError):
        run_simulation(
            SimulationParams(
                bath="bosonic",
                model="pure-dephasing",
                spectral="ohmic",
                N=1,
                epsilon=4.0,
                delta0=0.0,
                delta=0.0,
            ),
            out,
            verbose=False,
        )


def test_solver_class_api_defaults_to_current_directory(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.chdir(tmp_path)
    solver = PureDephasingSolver(system=SystemParams(N=1, epsilon=4.0))
    result = solver.run(RunConfig(verbose=False))
    assert result.output_dir == tmp_path
    assert (tmp_path / "exact-correlated.dat").exists()


def test_no_verify_reports_unchecked_exact_run(tmp_path: Path) -> None:
    result = run_simulation(
        SimulationParams(
            bath="bosonic",
            model="pure-dephasing",
            spectral="ohmic",
            N=1,
            epsilon=4.0,
            delta0=0.0,
            delta=0.0,
        ),
        tmp_path / "pure-no-verify",
        verify=False,
        verbose=False,
    )
    assert result.verification_performed is False
    assert result.exact_correlated_error is None


@pytest.mark.solver_rerun
def test_run_bosonic_spin_boson_n2(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(bath="bosonic", model="spin-boson", spectral="ohmic", observable="jx", N=2),
        tmp_path / "spin-boson-n2",
        verify=True,
    )
    assert result.correlated_error is not None
    assert result.correlated_error <= 1.0e-6
    assert result.uncorrelated_error is not None
    assert result.uncorrelated_error <= 1.0e-6
    assert (result.output_dir / "observable-correlated.dat").read_text().startswith("# Generated by")
    assert "input_mode: generated" in (result.output_dir / "observable-correlated.dat").read_text()
    assert (result.output_dir / "EXPX-C.DAT").exists()
    assert (result.output_dir / "sources" / "correlated_solver.f").exists()
    assert (result.output_dir / "sources" / "dimensions.inc").exists()
    assert (result.output_dir / "INSTATE.dat").exists()
    assert result.log_files is not None
    assert "correlated_compile_stderr" in result.log_files
    with pytest.raises(FileExistsError):
        run_simulation(
            SimulationParams(bath="bosonic", model="spin-boson", spectral="ohmic", observable="jx", N=2),
            result.output_dir,
            verify=False,
            verbose=False,
        )


@pytest.mark.solver_rerun
def test_run_bosonic_spin_boson_n4(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(bath="bosonic", model="spin-boson", spectral="ohmic", observable="jx", N=4),
        tmp_path / "spin-boson-n4",
        verify=True,
    )
    assert result.correlated_error is not None
    assert result.correlated_error <= 2.0e-6


@pytest.mark.solver_rerun
def test_run_bosonic_jx2_n4(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(
            bath="bosonic",
            model="spin-boson",
            spectral="ohmic",
            observable="jx^2",
            N=4,
            epsilon=3.5,
        ),
        tmp_path / "jx2-n4",
        verify=True,
    )
    assert result.correlated_error is not None
    assert result.correlated_error <= 2.5e-6
    assert (result.output_dir / "observable-correlated.dat").exists()
    assert not (result.output_dir / "EXPX-C.DAT").exists()


@pytest.mark.solver_rerun
def test_run_bosonic_subohmic_n4(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(bath="bosonic", model="spin-boson", spectral="subohmic", observable="jx", N=4, s=0.5),
        tmp_path / "subohmic-n4",
        verify=True,
    )
    assert result.correlated_error is not None
    assert result.correlated_error <= 2.0e-3


@pytest.mark.solver_rerun
def test_run_spin_bath_n4(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(bath="spin", model="spin-environment", spectral="ohmic", observable="jx", N=4),
        tmp_path / "spin-bath-n4",
        verify=True,
    )
    assert result.correlated_error is not None
    assert result.correlated_error <= 5.0e-7


@pytest.mark.solver_rerun
def test_run_spin_bath_jx2_without_reference(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(bath="spin", model="spin-environment", spectral="ohmic", observable="jx^2", N=4),
        tmp_path / "spin-bath-jx2-n4",
        verify=True,
        verbose=False,
    )
    assert result.example is None
    assert result.verification_performed is False
    assert (result.output_dir / "observable-correlated.dat").exists()


@pytest.mark.solver_rerun
def test_run_superohmic_bosonic_observable_sum(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(
            bath="bosonic",
            model="spin-boson",
            spectral="superohmic",
            observable="jx+jy",
            N=2,
            s=3.0,
        ),
        tmp_path / "superohmic-sum",
        verify=True,
        verbose=False,
    )
    assert result.example is None
    assert result.verification_performed is False
    assert (result.output_dir / "bathcorrelation.dat").exists()


@pytest.mark.solver_rerun
def test_run_arbitrary_bosonic_spin_boson_parameters_without_reference(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(
            bath="bosonic",
            model="spin-boson",
            spectral="ohmic",
            observable="jx",
            N=2,
            epsilon0=3.75,
            epsilon=2.25,
            delta0=0.4,
            delta=0.35,
            beta=0.8,
            coupling=0.03,
            omega_c=4.0,
        ),
        tmp_path / "arbitrary-spin-boson",
        verify=True,
        verbose=False,
    )
    assert result.example is None
    assert result.verification_performed is False
    assert result.correlated_error is None
    assert (result.output_dir / "observable-correlated.dat").exists()
    assert (result.output_dir / "params.in").exists()


@pytest.mark.solver_rerun
def test_spin_bath_subohmic_jy_with_user_numerics(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(bath="spin", model="spin-environment", spectral="subohmic", observable="jy", N=2, s=0.5),
        tmp_path / "spin-subohmic-jy",
        verify=False,
        verbose=False,
        numerics=FAST_NUMERICS,
    )
    assert result.verification_performed is False
    assert "tau_points: 41" in (result.output_dir / "bathcorrelation.dat").read_text()


@pytest.mark.solver_rerun
def test_spin_bath_superohmic_jz_saves_density(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    result = run_simulation(
        SimulationParams(bath="spin", model="spin-environment", spectral="superohmic", observable="jz", N=2, s=3.0),
        tmp_path / "spin-superohmic-jz-density",
        verify=False,
        verbose=False,
        save_density=True,
        numerics=FAST_NUMERICS,
    )
    assert (result.output_dir / "density-correlated.dat").exists()
    assert (result.output_dir / "EXPZ-C.DAT").exists()


@pytest.mark.solver_rerun
def test_bosonic_custom_matrix_observable_and_initial_state(tmp_path: Path) -> None:
    if not _compiler_ready():
        pytest.skip("gfortran not available")
    custom_observable = np.eye(3, dtype=complex) / 2.0
    custom_initial = np.eye(3, dtype=complex) / 3.0
    result = run_simulation(
        SimulationParams(
            bath="bosonic",
            model="spin-boson",
            spectral="superohmic",
            observable=custom_observable,
            N=2,
            s=2.0,
            initial_state=custom_initial,
        ),
        tmp_path / "bosonic-custom-matrix-state",
        verify=False,
        verbose=False,
        numerics=FAST_NUMERICS,
    )
    assert result.example is None
    assert "observable: custom_matrix" in (result.output_dir / "observable-correlated.dat").read_text()
    assert "initial_state_source: user_supplied" in (result.output_dir / "INSTATE.dat").read_text()
