		
		
	MODULE FUNCTION_CONTAINER
	IMPLICIT NONE
	SAVE
		
	INTEGER, PARAMETER :: DBL = SELECTED_REAL_KIND(P = 15,R = 200)

	REAL(KIND = DBL), PARAMETER :: JSYS = 0.5D0 !CHANGE HERE
	INTEGER, PARAMETER :: DIMSYS = NINT(2*JSYS + 1)
	INTEGER, PARAMETER :: DIMMAT = DIMSYS * DIMSYS

	COMPLEX*16, PARAMETER :: IMU = (0.0D0, 1.0D0)
	
	REAL(KIND = DBL), DIMENSION(DIMSYS)::ENERGIES
	COMPLEX*16, DIMENSION(DIMSYS,DIMSYS) :: EIGENSTATES
	REAL(KIND = DBL), DIMENSION(DIMSYS,DIMSYS) :: F
	COMPLEX*16, DIMENSION(DIMSYS,DIMSYS) :: BASISSTATES

	COMPLEX*16, DIMENSION(DIMMAT,1) :: INSTATE_BASISSTATES
	REAL*16, DIMENSION(DIMMAT) :: INSTATE_TEMP
	
	
	REAL(KIND = DBL), DIMENSION(2001)::NUARRAY
	COMPLEX*16, DIMENSION(2001) :: ADATA, BDATA, CDATA
	
	REAL(KIND = DBL) :: TEMPERATURE, G, OMEGAC

	REAL(KIND = DBL) :: DELTA, ENERGYGAP, OMEGADRIVE

	REAL(KIND = DBL) :: STEPSIZE_TAU, STEPSIZE_T

	REAL(KIND = DBL) :: TCUTOFF

	COMPLEX*16, DIMENSION(DIMSYS,DIMSYS)::Jz,Jx,Jy,ID

	COMPLEX*16, DIMENSION(DIMSYS,DIMSYS)::Jx_EB,Jy_EB, Jz_EB

	COMPLEX*16, DIMENSION(DIMSYS,DIMSYS) :: INSTATE

	COMPLEX*16, DIMENSION(DIMSYS,DIMSYS) :: INSTATE_EB
		
		
	CONTAINS
		
	INTEGER FUNCTION KRONDELTA(M,N)
	IMPLICIT NONE
	INTEGER, INTENT(IN)::N,M
	IF (N == M) THEN
		KRONDELTA = 1
	ELSE
		KRONDELTA = 0
	END IF
	END FUNCTION KRONDELTA

	SUBROUTINE MATJz(MATOUT)
	IMPLICIT NONE
	COMPLEX*16,DIMENSION(DIMSYS,DIMSYS),INTENT(OUT)::MATOUT
	INTEGER::K,L
	DO K = 1,DIMSYS
	DO L = 1,DIMSYS
	MATOUT(K,L) = ((JSYS+1) - K)*KRONDELTA(K,L)
	END DO
	END DO
	END SUBROUTINE MATJz

	SUBROUTINE MATJplus(MATOUT)
	IMPLICIT NONE
	COMPLEX*16,DIMENSION(DIMSYS,DIMSYS),INTENT(OUT)::MATOUT
	INTEGER::K,L
	REAL(KIND = DBL) :: M,MP
	DO K = 1,DIMSYS
	DO L = 1,DIMSYS
	MP = (JSYS + 1.0D0) - L
	M = (JSYS + 1.0D0) - K
	MATOUT(K,L) = DSQRT(JSYS*(JSYS+1.0D0) - M * (M + 1.0D0))
     &  		* KRONDELTA(NINT(2*MP),NINT(2*(M + 1)))
	END DO 	
	END DO
	END SUBROUTINE MATJplus

	SUBROUTINE MATJminus(MATOUT)
	IMPLICIT NONE
	COMPLEX*16,DIMENSION(DIMSYS,DIMSYS),INTENT(OUT)::MATOUT
	INTEGER::K,L
	REAL(KIND = DBL)::M,MP
	DO K = 1,DIMSYS
	DO L = 1,DIMSYS
	MP = (JSYS + 1.0D0) - L
	M = (JSYS + 1.0D0) - K
	MATOUT(K,L) = DSQRT(JSYS*(JSYS+1.0D0) - M * (M - 1.0D0)) 
     &			* KRONDELTA(NINT(2*MP),NINT(2*(M - 1)))
	END DO 	
	END DO
	END SUBROUTINE MATJminus

	SUBROUTINE MATJx(MATOUT)
	IMPLICIT NONE
	COMPLEX*16,DIMENSION(DIMSYS,DIMSYS),INTENT(OUT)::MATOUT
	COMPLEX*16,DIMENSION(DIMSYS,DIMSYS)::Jp,Jm
	CALL MATJplus(Jp)
	CALL MATJminus(Jm)
	MATOUT = (Jp + Jm)/2.0D0
	END SUBROUTINE MATJx

	SUBROUTINE MATJy(MATOUT)
	IMPLICIT NONE
	COMPLEX*16,DIMENSION(DIMSYS,DIMSYS),INTENT(OUT)::MATOUT
	COMPLEX*16,DIMENSION(DIMSYS,DIMSYS)::Jp,Jm
	CALL MATJplus(Jp)
	CALL MATJminus(Jm)
	MATOUT = (Jp - Jm)/(2.0D0 * IMU)
	END SUBROUTINE


	SUBROUTINE MATID(MATOUT)
	IMPLICIT NONE
	COMPLEX*16,DIMENSION(DIMSYS,DIMSYS),INTENT(OUT)::MATOUT
	INTEGER :: J
	MATOUT(:,:) = (0.0D0,0.0D0)
	DO J = 1, DIMSYS
	MATOUT(J,J) = (1.0D0,0.0D0)
	END DO
	END SUBROUTINE MATID

	SUBROUTINE INDEXCONVERTER(N,K,L)
	IMPLICIT NONE
	INTEGER, INTENT(IN)::N
	INTEGER, INTENT(OUT)::K,L
	INTEGER::X, REMAINDER
	X = N/DIMSYS
	REMAINDER = N - (X * DIMSYS)
	IF (REMAINDER == 0) THEN 
	K = X
	L = DIMSYS
	ELSE
	K = X + 1
	L = REMAINDER
	END IF
	END SUBROUTINE INDEXCONVERTER

	SUBROUTINE DENSITYMATRIX(X,RHO)
	IMPLICIT NONE
	COMPLEX*16, DIMENSION(DIMMAT,1),INTENT(IN)::X
	COMPLEX*16, DIMENSION(DIMSYS,DIMSYS),INTENT(OUT)::RHO
	INTEGER :: J, K, L
	DO J = 1, DIMMAT
	CALL INDEXCONVERTER(J,K,L)
	RHO(K,L) = X(J,1)
	END DO
	END SUBROUTINE DENSITYMATRIX

	SUBROUTINE EXPECTATION(X,A,ANS)
	IMPLICIT NONE
	COMPLEX*16, DIMENSION(DIMMAT,1),INTENT(IN) :: X
	COMPLEX*16, DIMENSION(DIMSYS,DIMSYS),INTENT(IN)::A
	REAL(KIND = DBL), INTENT(OUT) :: ANS
	COMPLEX*16, DIMENSION(DIMSYS, DIMSYS)::RHO
	COMPLEX*16, DIMENSION(DIMSYS, DIMSYS) :: TEMP
	INTEGER :: J
	REAL(KIND = DBL)::SUMM
	SUMM = 0.0D0
	CALL DENSITYMATRIX(X,RHO)
	TEMP = MATMUL(A,RHO)
	DO J = 1, DIMSYS
	SUMM = SUMM + DREAL(TEMP(J,J))
	END DO
	ANS = SUMM
	END SUBROUTINE EXPECTATION

	SUBROUTINE SURVIVALPROBABILITY(X,PROB)
	IMPLICIT NONE
	COMPLEX*16, DIMENSION(DIMMAT,1),INTENT(IN) :: X
	REAL(KIND = DBL), INTENT(OUT) :: PROB
	COMPLEX*16, DIMENSION(DIMSYS, DIMSYS)::RHO
	COMPLEX*16, DIMENSION(DIMSYS, DIMSYS) :: TEMP
	INTEGER :: J
	REAL(KIND = DBL)::SUMM
	SUMM = 0.0D0
	CALL DENSITYMATRIX(X,RHO)
	TEMP = MATMUL(INSTATE_EB,RHO)
	DO J = 1, DIMSYS
	SUMM = SUMM + DREAL(TEMP(J,J))
	END DO
	PROB = SUMM
	END SUBROUTINE SURVIVALPROBABILITY
	
		
	REAL (KIND = DBL) FUNCTION ENERGYDIFF(M,N)
	IMPLICIT NONE
	INTEGER, INTENT(IN)::N,M
	ENERGYDIFF = ENERGIES(M) - ENERGIES(N)
	END FUNCTION ENERGYDIFF
	
	
	SUBROUTINE COHEVOL(DARRAY)
	IMPLICIT NONE
	COMPLEX*16,DIMENSION(DIMMAT,DIMMAT),INTENT(OUT)::DARRAY
	INTEGER :: I,J,L1,L2,L3,L4
	DARRAY(:,:) = (0.0D0,0.0D0)
	DO I = 1,DIMMAT
	DO J = 1,DIMMAT
	CALL INDEXCONVERTER(I,L1,L2)
	CALL INDEXCONVERTER(J,L3,L4)
	IF (L1 == L3 .AND. L2 == L4) THEN
	DARRAY(I,J) = IMU * ENERGYDIFF(L2,L1)
	END IF
	END DO
	END DO
	END SUBROUTINE COHEVOL
	 
			
	COMPLEX*16 FUNCTION FMN(M,N)
	IMPLICIT NONE
	INTEGER, INTENT(IN) :: M,N
	COMPLEX*16, DIMENSION(DIMSYS) :: TEMP
	TEMP = MATMUL(F,BASISSTATES(:,N))
	FMN = DOT_PRODUCT(BASISSTATES(:,M), TEMP)
	END FUNCTION FMN

	SUBROUTINE UROT(UMAT)
	IMPLICIT NONE
	COMPLEX*16, DIMENSION(DIMSYS,DIMSYS),INTENT(OUT)::UMAT
	INTEGER::I,J
	DO I = 1, DIMSYS
	DO J = 1, DIMSYS
C	UMAT(I,J) = DOT_PRODUCT(EIGENSTATES(:,I),ID(:,J))
	UMAT(I,J) = DCONJG(EIGENSTATES(J,I))
	END DO 
	END DO
	END SUBROUTINE UROT


	SUBROUTINE INSTATETOX_EB(X)
	IMPLICIT NONE
	COMPLEX*16, DIMENSION(DIMMAT,1),INTENT(OUT)::X
	COMPLEX*16, DIMENSION(DIMSYS, DIMSYS):: MATRIX
	COMPLEX*16, DIMENSION(DIMSYS, DIMSYS)::R
	COMPLEX*16, DIMENSION(DIMSYS, DIMSYS)::RT
	INTEGER :: K,L,J
	CALL UROT(R)
	RT = DCONJG(TRANSPOSE(R))
	MATRIX = MATMUL(R,MATMUL(INSTATE,RT))
	DO K = 1, DIMSYS
	DO L = 1, DIMSYS
	J = (K - 1)*DIMSYS + L
	X(J,1) = MATRIX(K,L)
	END DO 
	END DO
	END SUBROUTINE INSTATETOX_EB


	SUBROUTINE MATRIX_EB(MATRIX, MATOUT)
	IMPLICIT NONE
	COMPLEX*16, DIMENSION(DIMSYS, DIMSYS),INTENT(IN)::MATRIX
	COMPLEX*16, DIMENSION(DIMSYS, DIMSYS),INTENT(OUT)::MATOUT
	COMPLEX*16, DIMENSION(DIMSYS, DIMSYS)::R
	COMPLEX*16, DIMENSION(DIMSYS, DIMSYS)::RT
	CALL UROT(R)
	RT = DCONJG(TRANSPOSE(R))
	MATOUT = MATMUL(R,MATMUL(MATRIX,RT))
	END SUBROUTINE MATRIX_EB

	SUBROUTINE DENSITYMATRIX_EB(X, MATOUT)
	IMPLICIT NONE
	COMPLEX*16,DIMENSION(DIMMAT, 1),INTENT(IN)::X
	COMPLEX*16,DIMENSION(DIMSYS, DIMSYS),INTENT(OUT)::MATOUT
	COMPLEX*16,DIMENSION(DIMSYS, DIMSYS)::RHO
	COMPLEX*16,DIMENSION(DIMSYS, DIMSYS)::R
	COMPLEX*16,DIMENSION(DIMSYS, DIMSYS)::RT
	CALL UROT(R)
	CALL DENSITYMATRIX(X,RHO)
	RT = DCONJG(TRANSPOSE(R))
	MATOUT = MATMUL(R,MATMUL(RHO,RT))
	END SUBROUTINE DENSITYMATRIX_EB
	 	
	COMPLEX*16 FUNCTION CORRELATOR(TAU) 		
	IMPLICIT NONE
	REAL(KIND = DBL), INTENT(IN)::TAU
	REAL(KIND = DBL) :: NU, ETA
	REAL(KIND = DBL) :: TEMP1, TEMP2
	INTEGER :: J
	J = NINT(TAU/0.0025D0)
	NU = G * NUARRAY(J + 1)
	TEMP1 = (2.0D0 * G * TAU)*OMEGAC**3.0D0
	TEMP2 = (1.0D0 + (TAU * OMEGAC)**2.0D0)**2.0D0
	ETA = TEMP1/TEMP2
	CORRELATOR = NU - IMU * ETA
	END FUNCTION CORRELATOR

	COMPLEX*16 FUNCTION WD(M,N,TAU)
	IMPLICIT NONE
	INTEGER, INTENT(IN)::M,N
	REAL(KIND = DBL), INTENT(IN)::TAU
	WD = (CDEXP(-IMU * ENERGYDIFF(M,N) * TAU)) * CORRELATOR(TAU)
	END FUNCTION WD
		
	COMPLEX*16 FUNCTION KD(M,N,B,A,TAU)
	IMPLICIT NONE
	INTEGER, INTENT(IN)::B,A,N,M
	REAL(KIND = DBL),INTENT(IN) :: TAU
	COMPLEX*16 :: T1,T2,T3
	COMPLEX*16 :: SUMM
	INTEGER :: L
	SUMM = (0.0D0,0.0D0)
	T1 = FMN(A,N)*FMN(M,B)*(WD(M,B,TAU)+DCONJG(WD(N,A,TAU)))
	DO L = 1, DIMSYS
	T2 = KRONDELTA(M,B)*FMN(L,N)*FMN(A,L)*DCONJG(WD(L,A,TAU))
	T3 = KRONDELTA(A,N)*FMN(M,L)*FMN(L,B)*WD(L,B,TAU)
	SUMM = SUMM + T2 + T3
	END DO
	KD = T1 - SUMM
	END FUNCTION KD
	
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	SUBROUTINE JRC(T,JK)
	IMPLICIT NONE
	REAL(KIND = DBL), INTENT(IN)::T
	COMPLEX*16, DIMENSION(DIMSYS,DIMSYS),INTENT(OUT)::JK
	INTEGER:: J
	COMPLEX*16 :: ADAT,BDAT,CDAT
	J = NINT(T/0.0025D0)
	ADAT = ADATA(J + 1)
	BDAT = BDATA(J + 1)
	CDAT = CDATA(J + 1)
	JK= G*(ADAT*Jx + BDAT*Jy + CDAT*Jz) !making changes here
	END SUBROUTINE JRC
	
	COMPLEX*16 FUNCTION JRCMN(N,M,T)
	IMPLICIT NONE
	REAL(KIND = DBL), INTENT(IN)::T
	INTEGER, INTENT(IN)::M,N
	COMPLEX*16, DIMENSION(DIMSYS,DIMSYS)::JK,JK_EB
	COMPLEX*16, DIMENSION(DIMSYS) :: TEMP
	CALL JRC(T,JK)
	TEMP = MATMUL(JK,BASISSTATES(:,N))!making changes here
	JRCMN = DOT_PRODUCT(BASISSTATES(:,M), TEMP)
	END FUNCTION JRCMN
	
	COMPLEX*16 FUNCTION TOTALL (M,N,B,A,T) 
	IMPlICIT NONE
	INTEGER, INTENT(IN)::M,N,B,A
	REAL(KIND = DBL),INTENT(IN) :: T
	COMPLEX*16 ::TEMP1,TEMP2,TEMP3,TEMP4,SUMM1,SUMM3,SUMM
	COMPLEX*16, DIMENSION(DIMSYS,DIMSYS)::JR,JRD
	INTEGER :: K,J
	SUMM1= (0.0D0,0.0D0)
	SUMM3= (0.0D0,0.0D0)
	DO K = 1, DIMSYS
	TEMP1=KRONDELTA(M,B)*JRCMN(A,K,T)*FMN(K,N)
	SUMM1=SUMM1+TEMP1
	END DO
	DO J = 1, DIMSYS
	TEMP3=FMN(M,J)*DCONJG(JRCMN(B,J,T))*KRONDELTA(A,N)
	SUMM3=SUMM3+TEMP3
	END DO
	TEMP2=FMN(M,B)*JRCMN(A,N,T)
	TEMP4=DCONJG(JRCMN(B,M,T))*FMN(A,N)
	SUMM =  SUMM1 - TEMP2 - SUMM3 + TEMP4
	TOTALL = -0.5D0*IMU*SUMM
	END FUNCTION TOTALL
	
	SUBROUTINE BRIG(T,ENDD)
	IMPLICIT NONE
	COMPLEX*16, DIMENSION(DIMMAT,DIMMAT),INTENT(OUT)::ENDD
	REAL(KIND = DBL), INTENT(IN):: T
	INTEGER :: I,J,L1,L2,L3,L4
	DO I = 1,DIMMAT
	DO J = 1,DIMMAT
	CALL INDEXCONVERTER(I,L1,L2)
	CALL INDEXCONVERTER(J,L3,L4)
	ENDD(I,J) = TOTALL(L1,L2,L3,L4,T)
	WRITE(9,*) T, ENDD(I,J)
	END DO
	END DO
	END SUBROUTINE BRIG
	
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	
	SUBROUTINE KERNEL(TAU,AKER)
	IMPLICIT NONE
	COMPLEX*16, DIMENSION(DIMMAT,DIMMAT),INTENT(OUT)::AKER
	REAL(KIND = DBL), INTENT(IN)::TAU
	INTEGER :: I,J,L1,L2,L3,L4
	DO I = 1,DIMMAT
	DO J = 1,DIMMAT
	CALL INDEXCONVERTER(I,L1,L2)
	CALL INDEXCONVERTER(J,L3,L4)
	AKER(I,J) = KD(L1,L2,L3,L4,TAU)
	END DO
	END DO
	END SUBROUTINE KERNEL
		
	SUBROUTINE INTEGRATOR(TMIN,T,ANS)
	IMPLICIT NONE
	COMPLEX*16, DIMENSION(DIMMAT,DIMMAT), INTENT(OUT)::ANS
	REAL(KIND = DBL), INTENT(IN)::TMIN,T
	COMPLEX*16, DIMENSION(DIMMAT,DIMMAT)::L1,L2,L3,L4,SUMM
	REAL(KIND = DBL)::TAU
	SUMM(:,:) = (0.0D0,0.0D0)
	TAU = TMIN
	DO WHILE ((T - TAU) > 0.000000001D0)
	CALL KERNEL(TAU,L1)
	CALL KERNEL(TAU + STEPSIZE_TAU,L2)
	CALL KERNEL(TAU + (STEPSIZE_TAU/2.0D0),L3)
	L4 = (L1 + L2) + 4.0D0*L3 
	SUMM = SUMM + (L4 *(STEPSIZE_TAU/6.0D0))
	TAU = TAU + STEPSIZE_TAU
	END DO
	ANS(:,:) = SUMM(:,:)
	END SUBROUTINE INTEGRATOR
		
	SUBROUTINE RUNGEKUTTA(T_MAX,ANSWER)
	IMPLICIT NONE
	REAL(KIND = DBL),INTENT(IN)::T_MAX
	COMPLEX*16, DIMENSION(DIMMAT,1), INTENT(OUT) :: ANSWER
	COMPLEX*16, DIMENSION(DIMMAT,1)::K_1,K_2,K_3,K_4,X
	COMPLEX*16, DIMENSION(DIMMAT,DIMMAT)::L1,L2,L3,P1,P2,P3,P4,P5
	COMPLEX*16, DIMENSION(DIMMAT,DIMMAT)::DELTAARRAY
	COMPLEX*16, DIMENSION(DIMMAT,DIMMAT)::INTEGRAL	
	REAL(KIND = DBL) :: Z_EXPECTATION, X_EXPECTATION
	REAL(KIND = DBL)::T
	COMPLEX*16, DIMENSION(DIMSYS,DIMSYS)::RHO_EB
	T = 0.00000000001D0
	INTEGRAL(:,:) = (0.0D0, 0.0D0)
	X = INSTATE_BASISSTATES
	CALL COHEVOL(DELTAARRAY)
	L1 = DELTAARRAY
	DO WHILE(T < T_MAX)
	CALL EXPECTATION(X,JZ_EB, Z_EXPECTATION)!making changes here
	WRITE(1,*) T, Z_EXPECTATION/JSYS
	CALL EXPECTATION(X,JX_EB, X_EXPECTATION) !making changes here
	WRITE(3,*) T, X_EXPECTATION/JSYS
	IF (T < TCUTOFF) THEN
	CALL INTEGRATOR(T,(T + STEPSIZE_T/2.0D0),P1)
	CALL INTEGRATOR(T, T + STEPSIZE_T,P2)
	CALL BRIG((T + STEPSIZE_T/2.0D0),P3)
	CALL BRIG(T + STEPSIZE_T,P4)
	L2 = DELTAARRAY + INTEGRAL + P1 + P3
	L3 = DELTAARRAY + INTEGRAL + P2 +P4
	INTEGRAL = INTEGRAL + P2  !making changes here
	END IF
	K_1 = MATMUL(L1,X)
	K_2=MATMUL(L2,(X+0.5D0*STEPSIZE_T*K_1))
	K_3=MATMUL(L2,(X+0.5D0*STEPSIZE_T*K_2))
	K_4 = MATMUL(L3,(X + (STEPSIZE_T*K_3)))
	X = X + ((STEPSIZE_T/6.0D0)*(K_1+2.0D0*K_2+2.0D0*K_3+K_4))
	T = T + STEPSIZE_T
	IF (T < TCUTOFF) THEN
	L1 = L3
	END IF
	END DO
	ANSWER = X
	END SUBROUTINE RUNGEKUTTA

		
		
	END MODULE FUNCTION_CONTAINER











C	THIS PROGRAM INVESTIGATES THE OPEN SYSTEM DYNAMICS 

	PROGRAM OPENSYSTEMDYNAMICS
	USE FUNCTION_CONTAINER
		
	IMPLICIT NONE
		
		
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	


C	VARIABLE DEFINITIONS.  BE CAREFUL TO CHANGE THEM. DO NOT CHANGE 
C	THE 4 IN D3
		

		

	COMPLEX*16, DIMENSION(DIMMAT,1)::ANS


	INTEGER :: J


	COMPLEX*16, DIMENSION(DIMSYS,DIMSYS)::HSYS, HSYSDUMMY, Jp,Jm

	COMPLEX*16,DIMENSION(2*DIMSYS)::D1	
	REAL(KIND = DBL),DIMENSION(3*DIMSYS - 2)::D2
	INTEGER::D3,KK,K1,K2

	COMPLEX*16, DIMENSION(DIMMAT,DIMMAT)::TEST
	
		


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	OPEN (1,FILE = 'EXPZ-C.DAT')

	OPEN (2,FILE = 'integraldatasimpson.dat')
	
	OPEN (3,FILE = 'EXPX-C.DAT')
	
	OPEN (4,FILE = 'A.dat')
	
	OPEN (5,FILE = 'B.dat')
	
	OPEN (7,FILE = 'C.dat')
	
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	CALL MATJz(Jz)
	CALL MATJx(Jx)
	CALL MATJy(Jy)
	CALL MATID(ID)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!



C	Assign values to variables here

	

	DELTA = 0.00D0
		
	ENERGYGAP = 4.0D0

	G = 0.05D0
		
	TEMPERATURE = 1.0D0 !This code is temperature independant
		
	OMEGAC = 5.0D0
		
	STEPSIZE_TAU = 0.005D0
	STEPSIZE_T = 0.01D0

	TCUTOFF = 15.0D0


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
		
		
C	CONSTRUCT THE HAMILTONIAN

	HSYS = (ENERGYGAP * JZ) + (DELTA * JX)

	HSYSDUMMY = HSYS


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


C	CONSTRUCT THE EIGENSYSTEM OF THE HAMILTONIAN

C	CALL DGEEV('N','V',DIMSYS,HSYS,DIMSYS,ENERGIES,D1,D2,DIMSYS,
C     &  EIGENSTATES,DIMSYS,D3,4*DIMSYS,D4)

	CALL 
     &	ZHEEV('V','U',DIMSYS,HSYSDUMMY,DIMSYS,ENERGIES,D1,
     &	2*DIMSYS,D2,D3)

	EIGENSTATES = HSYSDUMMY
	
     
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


	BASISSTATES = EIGENSTATES

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	
!	INSTATE READER
	OPEN (8,FILE = 'INSTATE-J=0.5.dat') !CHANGE HERE
	DO KK=1,DIMMAT
	READ(8,*) INSTATE_TEMP(KK)
	END DO
	DO KK=1,DIMMAT
	CALL INDEXCONVERTER(KK,K1,K2)
	INSTATE(K1,K2)=INSTATE_TEMP(KK)
	END DO
	CLOSE (8)	
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	CALL INSTATETOX_EB(INSTATE_BASISSTATES)


	CALL MATRIX_EB(Jz,Jz_EB)
	CALL MATRIX_EB(Jy,Jy_EB)
	CALL MATRIX_EB(Jx,Jx_EB)
	CALL MATRIX_EB(INSTATE,INSTATE_EB)
	
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

C	NOW INPUT THE SYSTEM OPERATOR

	F = Jz !making changes here

		
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
		
C	PUT IN THE ARRAY OF NU VALUES

	DO J = 1, 2001
	READ (2,*) NUARRAY(J)
	END DO
	
	DO J = 1, 2001
	READ (4,*) ADATA(J)
	END DO
	
	DO J = 1, 2001
	READ (5,*) BDATA(J)
	END DO
	
	DO J = 1, 2001
	READ (7,*) CDATA(J)
	END DO
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	
		
	CALL RUNGEKUTTA(5.0D0,ANS)
		
	WRITE (*,*) ANS

			
	CLOSE (1)

	CLOSE (2)

	CLOSE (3)
		
	CLOSE (4)
	
	CLOSE (5)
	
	CLOSE (7)	

	END PROGRAM OPENSYSTEMDYNAMICS
		
		
		




		
		
		

		

		
		
